# Pandas

O Pandas é uma biblioteca em Python para manipulação e análise de dados. Oferece estruturas e operações para manipular tabelas numéricas e séries. O nome é derivado do termo em inglês panel data (dados em painel), um termo usado em estatística para conjunto de dados.

In [91]:
import pandas as pd
import numpy as np

In [92]:
serie = pd.Series([1, 3, 5, 7, 11])

# A criação de uma série no Pandas se dá através da instrução Series.

In [93]:
print('Essa é uma estrutura de série no Pandas:')
print(serie)

Essa é uma estrutura de série no Pandas:
0     1
1     3
2     5
3     7
4    11
dtype: int64


In [94]:
indice = np.array(['A', 'B', 'C', 'D', 'E'])

In [95]:
serie = pd.Series([1, 3, 5, 7, 11], index=indice)

# Também podemos criar uma série com um índice nomeado.

In [96]:
print('Essa é uma estrutura de série com um índice nomeado no Pandas:')
print(serie)

Essa é uma estrutura de série com um índice nomeado no Pandas:
A     1
B     3
C     5
D     7
E    11
dtype: int64


In [97]:
indice_datas = pd.date_range("20220101", periods=6)

# É possível utilizar o método data_range para criar um intervalo de datas.
# Usaremos esse intervalo como índice do nosso dataframe.

In [98]:
print("Abaixo está a estrutura que contém o índice das datas:")
print(indice_datas)

Abaixo está a estrutura que contém o índice das datas:
DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')


In [99]:
array_aleatorio = np.empty((6,4), dtype=np.int32)

# O método empty do NumPy está sendo usado para criar os dados que simularemos no nosso dataframe.

In [100]:
print("Abaixo está o nosso array aleatório que representa os dados do dataframe:")
print(array_aleatorio)

Abaixo está o nosso array aleatório que representa os dados do dataframe:
[[ 0  0  1  0]
 [ 2  0  3  0]
 [ 1  0  1  0]
 [ 1  0  1  0]
 [12  0  5  0]
 [ 6  0  9  0]]


In [101]:
dataframe = pd.DataFrame(array_aleatorio, index=indice_datas, columns=['A', 'B', 'C', 'D'])

# O dataframe é composto dos dados do nosso array, 
# tendo como índice das linhas as datas que foram geradas e as colunas as letras A, B, C e D.

In [102]:
print("Abaixo está nosso dataframe:")
print(dataframe)

Abaixo está nosso dataframe:
             A  B  C  D
2022-01-01   0  0  1  0
2022-01-02   2  0  3  0
2022-01-03   1  0  1  0
2022-01-04   1  0  1  0
2022-01-05  12  0  5  0
2022-01-06   6  0  9  0


O dataframe pode comportar dados de tipos diferentes.
Por isso, uma das formas mais interessantes de compor esta estrutura é através de um dicionário.

In [103]:
dataframe = pd.DataFrame({
                            "A": 1.0,
                            "B": pd.Timestamp("20221028"),
                            "C": pd.Series([1.2, 3.7, 5.5, 6], dtype="float32"),
                            "D": np.array([12,5,6,9], dtype="int32"),
                            "E": pd.Categorical(["novo", "usado", "usado", "novo"])
    })
print("Abaixo está o nosso dataframe construído a partir de um dicionário:")
print(dataframe)

# Como conteúdo do dicionário que forma nosso dataframe, 
# colocamos as colunas como chaves e os dados como valores.

Abaixo está o nosso dataframe construído a partir de um dicionário:
     A          B    C   D      E
0  1.0 2022-10-28  1.2  12   novo
1  1.0 2022-10-28  3.7   5  usado
2  1.0 2022-10-28  5.5   6  usado
3  1.0 2022-10-28  6.0   9   novo


### Os dataframes são muito poderosos e possuem uma série de funções para a visualização de dados.

In [104]:
print("Abaixo está a parte de cima do nosso dataframe:")
print(dataframe.head())

# O método head() exibe os elementos da parte de cima do dataframe.

Abaixo está a parte de cima do nosso dataframe:
     A          B    C   D      E
0  1.0 2022-10-28  1.2  12   novo
1  1.0 2022-10-28  3.7   5  usado
2  1.0 2022-10-28  5.5   6  usado
3  1.0 2022-10-28  6.0   9   novo


In [105]:
print("Abaixo está a parte de baixo do nosso dataframe:")
print(dataframe.tail(2))

# O método tail() exibe os elementos da parte de cima do dataframe.

Abaixo está a parte de baixo do nosso dataframe:
     A          B    C  D      E
2  1.0 2022-10-28  5.5  6  usado
3  1.0 2022-10-28  6.0  9   novo


In [106]:
print("Abaixo estão os índices do nosso dataframe:")
print(dataframe.index)

# O atributo index exibe os índices da parte do dataframe.

Abaixo estão os índices do nosso dataframe:
RangeIndex(start=0, stop=4, step=1)


In [107]:
print("Abaixo estão as colunas do nosso dataframe:")
print(dataframe.columns)

# O atributo columns exibe as colunas da parte do dataframe.

Abaixo estão as colunas do nosso dataframe:
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [108]:
print("Abaixo está nosso dataframe convertido para um array numpy:")
print(dataframe.to_numpy())

# O método to_numpy() retorna os elementos do dataframe como um ndarray.

Abaixo está nosso dataframe convertido para um array numpy:
[[1.0 Timestamp('2022-10-28 00:00:00') 1.2000000476837158 12 'novo']
 [1.0 Timestamp('2022-10-28 00:00:00') 3.700000047683716 5 'usado']
 [1.0 Timestamp('2022-10-28 00:00:00') 5.5 6 'usado']
 [1.0 Timestamp('2022-10-28 00:00:00') 6.0 9 'novo']]


In [109]:
print("Abaixo estão estatísticas básicas dobre nosso dataframe:")
print(dataframe.describe())

# O método describe() realiza operações de estatística básica.

Abaixo estão estatísticas básicas dobre nosso dataframe:
         A         C          D
count  4.0  4.000000   4.000000
mean   1.0  4.100000   8.000000
std    0.0  2.171021   3.162278
min    1.0  1.200000   5.000000
25%    1.0  3.075000   5.750000
50%    1.0  4.600000   7.500000
75%    1.0  5.625000   9.750000
max    1.0  6.000000  12.000000


In [110]:
print("Abaixo está nosso dataframe ordenado por uma coluna:")
print(dataframe.sort_values(by="D"))

# O método sort_values() ordena os dados de uma coluna.

Abaixo está nosso dataframe ordenado por uma coluna:
     A          B    C   D      E
1  1.0 2022-10-28  3.7   5  usado
2  1.0 2022-10-28  5.5   6  usado
3  1.0 2022-10-28  6.0   9   novo
0  1.0 2022-10-28  1.2  12   novo


### Existem diversas operações que podemos realizar com dataframes

In [111]:
print("Abaixo exibimos os dados da coluna C")
print(dataframe["C"])

# Podemos exibir os dados de uma coluna específica, indicando entre colchetes o valor dessa coluna

Abaixo exibimos os dados da coluna C
0    1.2
1    3.7
2    5.5
3    6.0
Name: C, dtype: float32


In [112]:
print("Abaixo exibimos apenas um intervalo de linhas")
print(dataframe[0:2])

# Um intervalo de linhas pode ser especificado, indicando primeiro a partir de que linha o corte 
# deve ser feito seguido da quantidade de linhas. Nesse caso, serão exibidas as duas primeiras.

Abaixo exibimos apenas um intervalo de linhas
     A          B    C   D      E
0  1.0 2022-10-28  1.2  12   novo
1  1.0 2022-10-28  3.7   5  usado


In [113]:
print("Abaixo exibimos apenas os valores do dataframe em que a coluna D seja maior do que 7")
print(dataframe[dataframe["D"] > 7])

# É possível fazer a exibição dos dados baseado em uma operação booleana. 
# Nesse caso só serão exibidas linhas onde a coluna D tenha valores maiores do que 7.

Abaixo exibimos apenas os valores do dataframe em que a coluna D seja maior do que 7
     A          B    C   D     E
0  1.0 2022-10-28  1.2  12  novo
3  1.0 2022-10-28  6.0   9  novo


In [114]:
print("Abaixo exibimos apenas os valores em que a coluna E contém o valor 'usado'")
print(dataframe[dataframe["E"].isin(["usado"])])

# Também é possível exibir apenas as linhas que contenham valores em um determinado intervalo, 
# através do método isin. Nesse caso, só serão exibidas linhas em que a coluna E contém o valor “usado”.

Abaixo exibimos apenas os valores em que a coluna E contém o valor 'usado'
     A          B    C  D      E
1  1.0 2022-10-28  3.7  5  usado
2  1.0 2022-10-28  5.5  6  usado


### Para a importação e exportação de dados, existem funções padrão no pandas.

In [115]:
print("Exportando dataframe para o formato csv.")
dataframe.to_csv("arquivo_csv.csv")

# É possível exportar um dataframe para o formato csv.

Exportando dataframe para o formato csv.


In [116]:
print("Exportando dataframe para o formato xlsx.")
dataframe.to_excel("arquivo_excel.xlsx", sheet_name="Sheet1")

# É possível também exportar para o formato Excel. Para isso o pacote openpyxl deve estar instalado.

Exportando dataframe para o formato xlsx.


In [117]:
dataframe = pd.read_csv("arquivo_csv.csv")
print("Aqui está o dataframe recuperado do arquivo csv:")
print(dataframe)

# A abertura do arquivo csv e conversão para o formato dataframe.

Aqui está o dataframe recuperado do arquivo csv:
   Unnamed: 0    A           B    C   D      E
0           0  1.0  2022-10-28  1.2  12   novo
1           1  1.0  2022-10-28  3.7   5  usado
2           2  1.0  2022-10-28  5.5   6  usado
3           3  1.0  2022-10-28  6.0   9   novo


In [118]:
dataframe = pd.read_excel("arquivo_excel.xlsx")
print("Aqui está o dataframe recuperado do arquivo xlsx:")
print(dataframe)

# A abertura do arquivo Excel e conversão para o formato dataframe.

Aqui está o dataframe recuperado do arquivo xlsx:
   Unnamed: 0  A          B    C   D      E
0           0  1 2022-10-28  1.2  12   novo
1           1  1 2022-10-28  3.7   5  usado
2           2  1 2022-10-28  5.5   6  usado
3           3  1 2022-10-28  6.0   9   novo
